<?php


/**
 * @file
 * Adds a Facebook feed processor to the Feeds module.
 */


/**
 * Implements hook_feeds_plugins().
 */
function feeds_fb_page_feeds_plugins() {
  $info = array();
  
    $info['FeedsFbPageParser'] = array(
      'name' => 'Facebook Page Parser',
      'description' => 'Parse Facebook Page feeds.',
      'help' => 'Use Facebook Graph API <a href="http://developers.facebook.com/tools/explorer/?method=GET&path=id">SimplePie</a> to parse Facebook Page feeds.',
      'handler' => array(
        'parent' => 'FeedsParser',// A plugin needs to derive either directly or indirectly from FeedsFetcher, FeedsParser or FeedsProcessor.
        'class' => 'FeedsFbPageParser',
        'file' => 'FeedsFbPageParser.inc',
        'path' => drupal_get_path('module', 'feeds_fb_page'),
      ),
    );
  
  return $info;
}


